name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --runtime linux-x64
    - name: Upload LNDManager Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: LNDManager.linux-x64.zip
        path: /home/runner/work/LNDManager/LNDManager/LNDManager/bin/Debug/net5.0/linux-x64/publish/
